"""empty message

Revision ID: 8af4a1e2c495
Revises: 
Create Date: 2024-12-04 10:05:03.806265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af4a1e2c495'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('continent', sa.String(), nullable=False),
    sa.Column('capital', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('driving_side', sa.String(), nullable=True),
    sa.Column('license_plate', sa.String(), nullable=True),
    sa.Column('bollard', sa.String(), nullable=True),
    sa.Column('chevron', sa.String(), nullable=True),
    sa.Column('utility_pole', sa.String(), nullable=True),
    sa.Column('curb', sa.String(), nullable=True),
    sa.Column('guardrail', sa.String(), nullable=True),
    sa.Column('lanes', sa.String(), nullable=True),
    sa.Column('stop_sign', sa.String(), nullable=True),
    sa.Column('pedestrian_sign', sa.String(), nullable=True),
    sa.Column('direction_sign', sa.String(), nullable=True),
    sa.Column('road_number', sa.String(), nullable=True),
    sa.Column('road_sign', sa.String(), nullable=True),
    sa.Column('sign_traffic_post', sa.String(), nullable=True),
    sa.Column('architecture', sa.String(), nullable=True),
    sa.Column('landscape', sa.String(), nullable=True),
    sa.Column('google_car', sa.String(), nullable=True),
    sa.Column('follow_car', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('rift', sa.String(), nullable=True),
    sa.Column('camera_gen', sa.String(), nullable=True),
    sa.Column('miscellaneous', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country')
    # ### end Alembic commands ###
